1번 과제

다음 주어진 10개의 x, y 데이터를 이용하여 5차까지의 polynomial regression을 만드시오.
외부 라이브러리, optimal form 둘 다 각각 만드시오.
 

In [1]:
height = [66, 68, 60, 70, 65, 61, 74, 73, 75, 67]
weight = [160, 170, 110, 178, 155, 120, 223, 215, 235, 164]

In [2]:
len(height)
len(weight)

10

In [13]:
import scipy as sp
import numpy as np
import math
from numpy import linalg as LA
def polynomial_regression(x, y, p):
  coefs = sp.polyfit(x, y, p)
  print(coefs)
p_list = [1, 2, 3, 4, 5]
for i in p_list:
  polynomial_regression(height, weight, i) # 외부 모듈을 이용한 coefficients 추출port scipy as sp
  import numpy as np
  import math
  from numpy import linalg as LA
  def polynomial_regression(x, y, p):
    coefs = sp.polyfit(x, y, p)
      print(coefs)
      p_list = [1, 2, 3, 4, 5]
      for i in p_list:
        polynomial_regression(height, weight, i) # 외부 모듈을 이용한 coefficients 추출
        
  

[   7.96180988 -367.60689083]
[ 0.08974148 -4.17787681 40.77094023]
[ 5.25818087e-02 -1.05381378e+01  7.09488569e+02 -1.58802027e+04]
[-4.10703622e-03  1.16583062e+00 -1.23470947e+02  5.79087719e+03
 -1.01441279e+05]
[-1.49684452e-03  5.02390738e-01 -6.72843541e+01  4.49474093e+03
 -1.49759779e+05  1.99101232e+06]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: scipy.polyfit is deprecated and will be removed in SciPy 2.0.0, use numpy.polyfit instead
  


In [34]:
y = np.c_[height]
print(y)

[[66]
 [68]
 [60]
 [70]
 [65]
 [61]
 [74]
 [73]
 [75]
 [67]]


In [101]:
def make_X(x, p):
  X = []
  for i in range(p + 1):
    X.append([x[j]**i for j in range(len(x))])
  A = [X[k] for k in range(len(X))]
  return np.c_[A].transpose()
  

In [102]:
print(make_X(height, 3))


[[     1     66   4356 287496]
 [     1     68   4624 314432]
 [     1     60   3600 216000]
 [     1     70   4900 343000]
 [     1     65   4225 274625]
 [     1     61   3721 226981]
 [     1     74   5476 405224]
 [     1     73   5329 389017]
 [     1     75   5625 421875]
 [     1     67   4489 300763]]


In [104]:
from numpy.linalg import inv
# optimal form에서의 coefficients 추출
def explicit_polynomial_regression_solution(p):
    x_data = make_X(height, p)
    y_data = weight
    coeffs = inv(x_data.transpose().dot(x_data)).dot(x_data.transpose()).dot(y_data)
    print(coeffs)

In [106]:
for i in p_list:
  explicit_polynomial_regression_solution(i)

[-367.60689083    7.96180988]
[40.77094022 -4.17787681  0.08974148]
[-1.58802025e+04  7.09488561e+02 -1.05381377e+01  5.25818081e-02]
[-1.01437886e+05  5.79067584e+03 -1.23466474e+02  1.16578654e+00
 -4.10687371e-03]
[-1.01441751e+05  5.79090535e+03 -1.23471573e+02  1.16583679e+00
 -4.10705894e-03  1.13406123e-15]


2번 과제
다음 real estate 파일을 이용하여 훈련 데이터를 370까지, 그 뒤는 테스트 데이터로 분리하라. 그 후 linear regression 함수를 찾고 SSE를 계산하여라.

In [179]:
import pandas as pd

df= pd.read_excel('/content/Real estate.xlsx')
df.head()


No  X1 transaction date  ...  X6 longitude  Y house price of unit area
0   1             2012.917  ...     121.54024                        37.9
1   2             2012.917  ...     121.53951                        42.2
2   3             2013.583  ...     121.54391                        47.3
3   4             2013.500  ...     121.54391                        54.8
4   5             2012.833  ...     121.54245                        43.1

[5 rows x 8 columns]

In [180]:
data_X = np.c_[df['X1 transaction date'] , df['X2 house age'], df['X3 distance to the nearest MRT station'],
             df['X4 number of convenience stores'], df['X5 latitude'], df['X6 longitude']]
data_Y = np.hstack(df['Y house price of unit area'])


In [181]:
data_train_X = data_X[:370]
data_train_Y = data_Y[:370]
data_test_X = data_X[370:]
data_test_Y = data_Y[370:]
print(data_train_Y)
print(data_train_X)

[ 37.9  42.2  47.3  54.8  43.1  32.1  40.3  46.7  18.8  22.1  41.4  58.1
  39.3  23.8  34.3  50.5  70.1  37.4  42.3  47.7  29.3  51.6  24.6  47.9
  38.8  27.   56.2  33.6  47.   57.1  22.1  25.   34.2  49.3  55.1  27.3
  22.9  25.3  47.7  46.2  15.9  18.2  34.7  34.1  53.9  38.3  42.   61.5
  13.4  13.2  44.2  20.7  27.   38.9  51.7  13.7  41.9  53.5  22.6  42.4
  21.3  63.2  27.7  55.   25.3  44.3  50.7  56.8  36.2  42.   59.   40.8
  36.3  20.   54.4  29.5  36.8  25.6  29.8  26.5  40.3  36.8  48.1  17.7
  43.7  50.8  27.   18.3  48.   25.3  45.4  43.2  21.8  16.1  41.   51.8
  59.5  34.6  51.   62.2  38.2  32.9  54.4  45.7  30.5  71.   47.1  26.6
  34.1  28.4  51.6  39.4  23.1   7.6  53.3  46.4  12.2  13.   30.6  59.6
  31.3  48.   32.5  45.5  57.4  48.6  62.9  55.   60.7  41.   37.5  30.7
  37.5  39.5  42.2  20.8  46.8  47.4  43.5  42.5  51.4  28.9  37.5  40.1
  28.4  45.5  52.2  43.2  45.1  39.7  48.5  44.7  28.9  40.9  20.7  15.6
  18.3  35.6  39.4  37.4  57.8  39.6  11.6  55.5  5

In [182]:
print(len(data_train))
print(len(data_test))

6
44


In [183]:
from sklearn.linear_model import LinearRegression

LR = LinearRegression() # sklearn에서 모델 사용
LR.fit(data_train_X, data_train_Y)
print(LR.coef_)
print(LR.intercept_)

[ 5.22546644e+00 -2.70431480e-01 -4.25853518e-03  1.13015730e+00
  2.56875318e+02 -9.97263765e+00]
-15678.8337730268


In [186]:
LR.predict(data_test_X) 
np.sum((LR.predict(data_test_X) - data_test_Y)**2) # sklearn 모델의 SSE 계산

3068.9345959586303

In [195]:
A_0 = [1 for i in range(len(data_train_X))]
new_X = np.c_[A_0, data_train_X]
print(new_X)

[[1.0000000e+00 2.0129170e+03 3.2000000e+01 ... 1.0000000e+01
  2.4982980e+01 1.2154024e+02]
 [1.0000000e+00 2.0129170e+03 1.9500000e+01 ... 9.0000000e+00
  2.4980340e+01 1.2153951e+02]
 [1.0000000e+00 2.0135830e+03 1.3300000e+01 ... 5.0000000e+00
  2.4987460e+01 1.2154391e+02]
 ...
 [1.0000000e+00 2.0128330e+03 1.5000000e+01 ... 2.0000000e+00
  2.4964640e+01 1.2151531e+02]
 [1.0000000e+00 2.0134170e+03 1.8200000e+01 ... 1.0000000e+00
  2.4975440e+01 1.2153119e+02]
 [1.0000000e+00 2.0126670e+03 2.0200000e+01 ... 3.0000000e+00
  2.4963220e+01 1.2151237e+02]]


In [204]:
from numpy.linalg import inv
# optimal form을 이용한 해 찾기
def explicit_linear_regression_solution():
    x_data = new_X
    y_data = data_train_Y
    coeffs = inv(x_data.transpose().dot(x_data)).dot(x_data.transpose()).dot(y_data)
    return coeffs

In [197]:
coef = explicit_linear_regression_solution() 
print(coef)

[-1.56788342e+04  5.22546638e+00 -2.70431480e-01 -4.25853513e-03
  1.13015730e+00  2.56875317e+02 -9.97263277e+00]


In [202]:
predict = []
for i in range(len(data_test_X)):
  sum = 0
  for j in range(len(coef) - 1):
    sum += data_test_X[i][j] * coef[j+1]
  sum += coef[0]
  predict.append(sum)

In [203]:
np.sum((predict - data_test_Y)**2) # 손코딩 SSE 계산

3068.9345399026897