In [1]:
import numpy as np
import torch

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 1
Shape of t: (7,)


In [6]:
print('t[0] t[1] t[-1] =', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) # Slicing
print('t[:2] t[3:]  = ', t[:2], t[3:]) # Slicing

t[0] t[1] t[-1] = 0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]  =  [0. 1.] [3. 4. 5. 6.]


In [7]:
t = np.array([[1., 2., 3.], [4., 5. ,6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 2
Shape of t: (4, 3)


In [9]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [10]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0], t[1], t[-1]) # Element
print(t[2:5], t[4:-1]) # Slicing
print(t[:2], t[3:]) # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [11]:
t = torch.FloatTensor([[1., 2., 3.], [4., 5. ,6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [12]:
print(t.dim()) # rank
print(t.size()) # shape
print(t[:, 1]) 
print(t[:, 1].size()) 
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


- Broadcasting

In [14]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [20]:
# Vector + scaler
m1 = torch.FloatTensor([[1, 2]]) # |m1| = (1, 2)  and |m2| = (1,) => (1, 2)
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [21]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # |m1| = (1, 2)     => (2, 2)
m2 = torch.FloatTensor([[3], [4]]) # |m2| = (2, 1)   => (2, 2)
'''
[1, 2] + [3, 3]
[1, 2] + [4, 4]
'''
print(m1 + m2)


tensor([[4., 5.],
        [5., 6.]])


In [23]:
print()
print('-' * 10)
print('Mul vs Matmul')
print('-' * 10)
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print("Shape of Matrix 1:", m1.shape) # 2 x 2
print("Shape of Matrix 2:", m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print("Shape of Matrix 1:", m1.shape) # 2 x 2
print("Shape of Matrix 2:", m2.shape) # 2 x 1      => 2 x 2 (Broad Casting)
'''
[1 2]   x  [1 1]
[3 4]   x  [2 2]
'''
print(m1 + m2) # 2 x 2
print(m1.mul(m2)) 



----------
Mul vs Matmul
----------
Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[2., 3.],
        [5., 6.]])
tensor([[1., 2.],
        [6., 8.]])


- Mean

In [24]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [25]:
# Can`t use mean() on integers
t = torch.LongTensor([1, 2]) # integers tensor
try:
  print(t.mean())
except Exception as exc:
  print(exc)

Can only calculate the mean of floating types. Got Long instead.


You can also ues t.mean for higher rank tensors to get mean of all elements, or mean by particular dimension

In [26]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [29]:
print(t.mean())
print(t.mean(dim=0)) # column 끼리의 합(2, 2) => (1, 2) 
print(t.mean(dim=1)) # row 끼리의 합(2, 2) => (2, 1)
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


- Sum

In [30]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [31]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


- Max and Argmax

In [39]:
t = torch.FloatTensor([[5, 100], [101, 8]])
print(t)

tensor([[  5., 100.],
        [101.,   8.]])


The max operator returns one value if it is called without an argument.

In [40]:
print(t.max()) # Returns one value: max

tensor(101.)


The max operator returns 2 values when called with dimension specified. The first value is the maximum value, and the second value is the argmax: the index of the element with maximum value.

In [42]:
print(t.max(dim = 0)) # Returns two values : max and argmax
print('Max: ', t.max(dim=0)[0]) # column 중에서 가장 큰 값을 뽑아옴
print('Argmax: ', t.max(dim=0)[1]) # max value index

torch.return_types.max(
values=tensor([101., 100.]),
indices=tensor([1, 0]))
Max:  tensor([101., 100.])
Argmax:  tensor([1, 0])


In [43]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([100., 101.]),
indices=tensor([1, 0]))
torch.return_types.max(
values=tensor([100., 101.]),
indices=tensor([1, 0]))
