<a href="https://colab.research.google.com/github/KCW-colab/study/blob/main/%EB%AA%A8%EB%91%90%EB%A5%BC%20%EC%9C%84%ED%95%9C%20%EB%94%A5%EB%9F%AC%EB%8B%9D/Lab_01_2_Tensor_Manipulation2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import numpy as np
import torch

# View ( Reshape )

In [51]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [52]:
print(ft.view([-1, 3]))  # -1 : i don`t know
print(ft.view([-1, 3]).shape)  # (2, 2, 3) => (4, 3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [53]:
print(ft.view([-1, 1, 3]))  # (2, 2, 3) => (2x2, 1, 3)
print(ft.view([-1 ,1 ,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


# Squeeze

In [54]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [55]:
print(ft.squeeze())  # dimension 1 짜리를 없애버린다.
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [56]:
print(ft.squeeze(dim=0))
print(ft.squeeze(dim=1))

tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])


# Unsqueeze ( squeeze를 다시 펼침 )

In [57]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [58]:
# 0번째 dimension에 1을 추가
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [59]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [60]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [61]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


# Type Casting

In [62]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [63]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [64]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [65]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


# Concatenate

In [66]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [67]:
print(torch.cat([x, y], dim = 0))
print(torch.cat([x, y], dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# Stacking

In [68]:
x = torch.FloatTensor([1, 4]) # |x| = |y| = |z| = (2, )
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [69]:
print(torch.stack([x, y, z])) # (3, 2)
print(torch.stack([x, y, z], dim = 1)) # (2, 3) 새로 생겨나는 dim인 3이 1번째로 감.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [70]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0)) # 차원을 늘려주고 붙임 (1, 2)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# Ones and Zeros

In [71]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x) # |x| = (2, 3)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [72]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# In-place Operation

In [73]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [76]:
print(x.mul(2.)) # broadcasting
print(x)
print(x.mul_(2.)) # data saving
print(x)

tensor([[ 8., 16.],
        [24., 32.]])
tensor([[ 4.,  8.],
        [12., 16.]])
tensor([[ 8., 16.],
        [24., 32.]])
tensor([[ 8., 16.],
        [24., 32.]])
